extends: stylelint-config-standard
plugins:
  - autoprefixer
  - postcss-import
  - postcss-scss
rules:
  - at-rule-empty-line-before: never
  - at-rule-name-case: lower
  - rule-empty-line-before: false
  - scss/at-rule-no-unknown: true
  - scss/at-rule-no-vendor-prefix: true
  - scss/max-nesting-depth: 3
  - scss/media-feature-name-no-vendor-prefix: true
  - scss/property-no-vendor-prefix: true
  - scss/selector-no-vendor-prefix: true
  - scss/value-no-vendor-prefix: true
